### ISSUE TITLE
Nes Hawk Auth: Uncaught error: header.match is not a function

### ISSUE THREAD

**Issue by salarelv** [hapijs/nes#181]
Hi, I have a API with a little bit custom Hawk authentication (the auth id is similar to Iron token). All my HTTP request are working fine. But when I try to connect with a Nes Client I get a error. Everything works also fine when the subscription has auth: false.

**Server**
```
server.register({
   register: Nes,
   options: {
      auth: {
	 type: "direct"
      }
   }
}, function(err) {
       console.log("nes error", err);
});
```
```
server.subscription('/device-running/{id}');
```

**Client**

```
     var token = {
	"key":"3c0e7b4d7af3d6e5d3a9",
	"id":"1-Fe26.2**c6db56b9c8cbfda10cee2a0994459f61b66250dfb0d074f9e1833e948d710f9a*isR168e1rdLnVhvk374nZQ*JGJ5RllmVYeVCVnIEpXDuIhtE431kirFuciC9geX4t6_iwArZsn-PtwMOoalRqm-GTC1wft5oHOO5FgfrEeYgabJPseKp_F-OxOsMyictOAAwqg1MgbsNIT0_OCGnceXH3gyktlkc-TPvmPKG8Zo1g**ceaa14588d9376b14fca7debcc07b5e4bc60b254f7a95ea11f2b5e96a15f533a*51nHQGVGGXvH1IfXmmXGwyt80tjJL1QTV9n6nFbVBX4",
	"algorithm":"sha256"
    };
    var id = "some-id";
    var client = new Nes.Client("ws://localhost:8080")
    var header = Hawk.client.header("ws://localhost:8080", "GET", { credentials: token });
    client.connect({ auth: { headers: { authorization: header } } }, function(err) {
	  console.log("Sender.connected", err, header);
	  client.subscribe('/device-running/' + id, function(data) {
	  });
    });
```
**Server log**
```
node_1    | Debug: internal, implementation, error 
node_1    |     TypeError: Uncaught error: header.match is not a function
node_1    |     at Object.exports.parseAuthorizationHeader (/usr/src/app/node_modules/hawk/lib/utils.js:128:30)
node_1    |     at Object.exports.authenticate (/usr/src/app/node_modules/hawk/lib/server.js:107:28)
node_1    |     at Object.authenticate (/usr/src/app/node_modules/hapi-auth-hawk/lib/index.js:37:25)
node_1    |     at request._protect.run (/usr/src/app/node_modules/hapi/lib/auth.js:336:34)
node_1    |     at internals.Protect.run (/usr/src/app/node_modules/hapi/lib/protect.js:62:12)
node_1    |     at execute (/usr/src/app/node_modules/hapi/lib/auth.js:332:30)
node_1    |     at authenticate (/usr/src/app/node_modules/hapi/lib/auth.js:318:21)
node_1    |     at internals.Auth._authenticate (/usr/src/app/node_modules/hapi/lib/auth.js:226:19)
node_1    |     at internals.Auth.authenticate (/usr/src/app/node_modules/hapi/lib/auth.js:197:17)
node_1    |     at each (/usr/src/app/node_modules/hapi/lib/request.js:380:16)
node_1    |     at iterate (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:36:13)
node_1    |     at done (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:28:25)
node_1    |     at Hoek.once (/usr/src/app/node_modules/hapi/lib/protect.js:52:16)
node_1    |     at wrapped (/usr/src/app/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
node_1    |     at done (/usr/src/app/node_modules/hapi/node_modules/items/lib/index.js:31:25)
node_1    |     at finalize (/usr/src/app/node_modules/hapi/lib/request.js:400:24)
node_1    | 127.0.0.1: AUTH /nes/auth --> 500
```
Seems like **hawk/lib/utils.js:128:30** expects a **String** but a _object_ is given. And it doesn't reach my getCredentials function.
Any ideas what Is wrong with my code?

**Comment by salarelv** [comment]
No advice?

**Comment by mtharrison** [comment]
Have a look at the client part of the [Hawk readme usage example](https://github.com/hueniverse/hawk/blob/master/README.md#usage-example). The `header` value returned by `Hawk.client.header()` is an object. To send in the HTTP header you want the string at `header.field`.

**Comment by mtharrison** [comment]
Closing this as it's not a Nes issue. If you need any more help with Hawk usage please open an issue on Hawk or Hapi-Auth-Hawk.

**Comment by salarelv** [comment]
Thanks. header.field was the issue
