### ISSUE TITLE
JWT Auth

### ISSUE THREAD

**Issue by sjzamora86** [hapijs/nes#183]
Does anyone managed to make [hapi-auth-jwt](https://github.com/ryanfitz/hapi-auth-jwt) to work for nes? I'm struggling to make this authentication to work. This works perfectly on hapi routes. Any help will be much appreciated.

**Comment by mtharrison** [comment]
Yes, it works. What have you tried? You'll get a better response if you can show what's going wrong for you.

**Comment by sjzamora86** [comment]
@mtharrison thanks for the reply. Please see the below information. 

My registration look like this:
```
{
        register: Nes,
        options: {
            auth: {
                type: 'token',
                index: true
            }
        }
    }
```
Server auth will be:
```
server.auth.strategy('token', 'jwt', {
            key: 'fakeToken',
            validateFunc: (request,
                           decodedToken,
                           callback) => {
                callback(null, true, {
                    user: decodedToken.user
                });
            },
            verifyOptions: {
                algorithms: ['HS256']
            }
        });
```
This allows the server to start but when the client connect I'm getting this error:
```
   const parts = sealed.split('*');
                         ^

TypeError: sealed.split is not a function
    at Object.exports.unseal (/Users/sjzamora86/Documents/myApp/source/server/node_modules/iron/lib/index.js:331:26)
    at internals.Socket._processHello (/Users/sjzamora86/Documents/myApp/source/server/node_modules/nes/lib/socket.js:352:10)
    at internals.parse (/Users/sjzamora86/Documents/myApp/source/server/node_modules/nes/lib/socket.js:239:25)
    at Object.internals.parse (/Users/sjzamora86/Documents/myApp/source/server/node_modules/nes/lib/socket.js:601:12)
    at internals.Socket._onMessage (/Users/sjzamora86/Documents/myApp/source/server/node_modules/nes/lib/socket.js:220:15)
    at WebSocket.ws.on (/Users/sjzamora86/Documents/myApp/source/server/node_modules/nes/lib/socket.js:42:40)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/sjzamora86/Documents/myApp/source/server/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/sjzamora86/Documents/myApp/source/server/node_modules/ws/lib/Receiver.js:536:18
    at /Users/sjzamora86/Documents/myApp/source/server/node_modules/ws/lib/Receiver.js:368:7
    at /Users/sjzamora86/Documents/myApp/source/server/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:385:3)
    at onwrite (_stream_writable.js:376:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at afterTransform (_stream_transform.js:79:3)
```

Client connecting this way:
```
client.connect({auth: {headers: {authorization: `Bearer ${token}`}}}, (error) => {
           ...do something
 });
```

**Comment by mtharrison** [comment]
I think you want the `direct` authentication method if you're providing your own credentials via the header.. Try removing `type: 'token',` from your Nes options.

**Comment by sjzamora86** [comment]
When I do this way, I can now able to connect however the socket.auth.credentials is undefined which I need. I've tried to do:

```
this.server.eachSocket((socket) => {
    console.log(socket.auth.credentials);
    /*
        Output:
        { 
            isAuthenticated: true,
            credentials: undefined,
            artifacts: undefined,
            _error: null,
            _timeout: null 
        }
    */
});
```

**Comment by mtharrison** [comment]
Are you sure auth is enabled for all routes? What happens if you set it as default required?
```
server.auth.strategy('token', 'jwt', true, options)?
```
Are you sure `decodedToken.user` is actually defined, did you try logging it in the validate function to ensure so?
